{{- if and .Values.gateway.enabled (eq .Values.gateway.serviceType "NodePort") .Values.gateway.nodePort.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.gateway.name }}-istio
  namespace: {{ .Values.gateway.namespace }}
  labels:
    {{- include "python-app.labels" . | nindent 4 }}
    gateway.istio.io/managed: istio.io-gateway-controller
    gateway.networking.k8s.io/gateway-name: {{ .Values.gateway.name }}
    istio.io/gateway-name: {{ .Values.gateway.name }}
  annotations:
    networking.istio.io/service-type: NodePort
spec:
  type: NodePort
  selector:
    gateway.networking.k8s.io/gateway-name: {{ .Values.gateway.name }}
  ports:
    - appProtocol: tcp
      name: status-port
      nodePort: {{ .Values.gateway.nodePort.statusPort }}
      port: 15021
      protocol: TCP
      targetPort: 15021
    - appProtocol: http
      name: http
      nodePort: {{ .Values.gateway.nodePort.http }}
      port: 80
      protocol: TCP
      targetPort: 80
    {{- if .Values.gateway.nodePort.https }}
    - appProtocol: https
      name: https
      nodePort: {{ .Values.gateway.nodePort.https }}
      port: 443
      protocol: TCP
      targetPort: 443
    {{- end }}
{{- end }}