{{- if .Values.gateway.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name | default (include "python-app.fullname" .) }}
  {{- if .Values.gateway.namespace }}
  namespace: {{ .Values.gateway.namespace }}
  {{- end }}
  labels:
    {{- include "python-app.labels" . | nindent 4 }}
  annotations:
    {{- if eq .Values.gateway.serviceType "NodePort" }}
    networking.istio.io/service-type: NodePort
    {{- else if eq .Values.gateway.serviceType "LoadBalancer" }}
    networking.istio.io/service-type: LoadBalancer
    {{- end }}
    {{- with .Values.gateway.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.gateway.infrastructure }}
  infrastructure:
    {{- toYaml .Values.gateway.infrastructure | nindent 4 }}
  {{- end }}
  gatewayClassName: {{ .Values.gateway.className | default "istio" }}
  listeners:
  - name: http
    hostname: {{ .Values.gateway.hotnamePattern | quote }}
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All
  {{- if .Values.gateway.nodePort.https }}
  - name: https
    hostname: {{ .Values.gateway.hotnamePattern | quote }}
    port: 443
    protocol: HTTPS
    tls:
      mode: Terminate
      certificateRefs:
        - name: {{ .Values.gateway.https.tlsSecretName }}
          kind: Secret
    allowedRoutes:
      namespaces:
        from: All
  {{- end }}
{{- end }}