{{- if .Values.gateway.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name | default (include "python-app.fullname" .) }}
  {{- if .Values.gateway.namespace }}
  namespace: {{ .Values.gateway.namespace }}
  {{- end }}
  labels:
    {{- include "python-app.labels" . | nindent 4 }}
  {{- with .Values.gateway.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.gateway.infrastructure }}
  infrastructure:
    {{- toYaml .Values.gateway.infrastructure | nindent 4 }}
  {{- end }}
  gatewayClassName: {{ .Values.gateway.className | default "istio" }}
  listeners:
    {{- toYaml .Values.gateway.listeners | nindent 4 }}
{{- end }}